### ISSUE TITLE
copy/paste

### ISSUE THREAD

**Issue by Piour** [alpha14/cozy-term#1]
Hi,

nice app !

I wanted to copy/paste some text from another website to the terminal and I couldn't figure out how to paste it into the terminal. Is there a way to do it ?

**Comment by Shuunen** [comment]
+1 :) copy/paste would be great

even if the app is aldready rocking ! :D

**Comment by alpha14** [comment]
The copy/paste is fixed here: https://github.com/alpha14/cozy-term/tree/patch1
There is one problem: Its not yet possible to install the updated app on a cozy instance.

**Comment by Shuunen** [comment]
Ah ? what is messing ?

**Comment by alpha14** [comment]
@Shuunen I'm not really sure, some dependency problem.

**Comment by alpha14** [comment]
I finally nailed the problem, shrinkwrap was not behaving in the same way on older versions of npm.

**Comment by Shuunen** [comment]
GG :)

**Comment by Piour** [comment]
:+1:

**Comment by Shuunen** [comment]
so there will be a new version of cozy-term ? in order to get this fix

**Comment by alpha14** [comment]
@Shuunen I already merged the fix in the master branch, you should be able to update the app in your cozy.

**Comment by Shuunen** [comment]
the cozy term I have is up-to-date in version 1.5.2 and ctrl+v doesn't paste anything in the commande line, weird

**Comment by Shuunen** [comment]
my bad, the right click / paste works, its great \o/

![image](https://cloud.githubusercontent.com/assets/439158/11296806/9dbcfb82-8f74-11e5-9642-e9fa86552a56.png)
