### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by clochix** [alpha14/cozy-term#2]
Installation fails with error:

```
Error: version not found: coffee@0.0.1
```

You should upgrade version of coffee to 1.0.0.

**Comment by alpha14** [comment]
Fixed, thanks @clochix

**Comment by clochix** [comment]
Thanks a lot, it works now !

**Comment by letoff** [comment]
Can't have a term which stays open more than a couple of seconds. Here are my logs:

[tty.js] 1 Client attempting to write to a non-existent terminal. (id: /dev/pts/15)
[tty.js] 1 Client attempting to write to a non-existent terminal. (id: /dev/pts/15)
 master: 23, pid: 11873).
[tty.js] 1 Session 1 created.
[tty.js] 1 Client attempting to write to a non-existent terminal. (id: /dev/pts/15)
[tty.js] 1 Client attempting to write to a non-existent terminal. (id: /dev/pts/15)

I love this app but wish I could really use it. :~)
