### ISSUE TITLE
Window closing just after opening

### ISSUE THREAD

**Issue by nicofrand** [alpha14/cozy-term#6]
How to reproduce:
- Close all windows in term
- Go to home
- Refresh the page
- Open term
- Click on "Open terminal"

It does not happen everytime I use it. If I click again on "Open terminal", it seems to work.

What happens:
- The window is opened but does not display my hostname nor my login (toto@server:)
- After a few seconds the window is shut

Term logs (on the server, nothing on the client side):

```
[tty.js] 2 Client attempting to write to a non-existent terminal. (id: )
[tty.js] 2 Client attempting to write to a non-existent terminal. (id: )
[tty.js] 2 Client attempting to write to a non-existent terminal. (id: )
[tty.js] 2 Client attempting to write to a non-existent terminal. (id: /dev/pts/2)
```

**Comment by alpha14** [comment]
I cannot reproduce this issue. Are you using a self-hosted version of cozy?

**Comment by nicofrand** [comment]
Yes I do

**Comment by nicofrand** [comment]
I cannot reproduce the issue since I solved my websocket issue.

**Comment by Zykino** [comment]
How did you solve your websocket issue? (Still happen in the [demo cozycloud](https://demo.cozycloud.cc) server)

**Comment by nicofrand** [comment]
I modified my apache configuration : https://github.com/cozy/cozy-debian/pull/23/commits/2690fadb1bccfeabd8069a95f0ebc63213d7a0d7. But that's another thing for the demo server I guess…
